name: Build & Push to DockerHub

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Docker Context Path'     
        required: true
        default: './ethereum'
      app:
        description: 'Image Name'
        required: true
        default: 'parity-ethereum'
      version:
        description: 'Image Tag'
        required: true
        default: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.event.inputs.path }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.app }}:${{ github.event.inputs.version }}